/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

import senet.Jogo;
import java.io.Serializable;

/**
 *
 * @author SnowBlade
 */
public class Jframe extends javax.swing.JFrame {
    private Object gui;
    
    

    public int width=this.getWidth();
    public int height=this.getHeight();
    public int lol=10+1*height/22;
    public int modo;
   
    
    /**
     * Creates new form window
     */
    public Jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel11 = new gui.Panel66();
        mensagemLabel = new javax.swing.JLabel();
        options = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Novojogopvp = new javax.swing.JButton();
        novojogoIA = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 300));

        panel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel11MouseClicked(evt);
            }
        });

        mensagemLabel.setBackground(new java.awt.Color(102, 51, 0));
        mensagemLabel.setFont(new java.awt.Font("Tahoma", 0, lol));
        mensagemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensagemLabel.setText(panel11.mensagem);
        mensagemLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Novojogopvp.setText("Novo jogo VS");
        Novojogopvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovojogopvpActionPerformed(evt);
            }
        });

        novojogoIA.setText("Novo jogo");
        novojogoIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojogoIAActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Continuar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Modo One Piece");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novojogoIA, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Novojogopvp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novojogopvp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novojogoIA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opcções", jPanel2);

        jTextArea2.setBackground(new java.awt.Color(102, 51, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("REGRAS SENET:\nCada jogador possui 5 peças e um dado.\n \nVence quem chegar a última casa com todas as peças (o número \nfinal deve ser exato para entrar  na última casa)\n\nO dado de jogo não possui a face nr 5 para manter as regras do jogo \noriginal, no qual eram utilizados pedaços de madeira ou ossos para \njogar.\n\nO jogador das brancas é o primeiro a conseguir obter '1' no dado. \n\nDe seguida, à vez, os jogadores vão lançando o dado e avançando \nas peças no tabuleiro. Se o jogador obter '1', '4' ou '6'  tem direito a \numa ronda extra, não havendo limites para as rondas extras.\n\nCada casa só pode conter uma peça, se a casa destino de uma peça \nestiver ocupada por outra da mesma cor o movimento é considerado \ninválido, mas se a peça for do adversário pode capturar a peça, \nocupando o seu lugar e forçando-a a recuar até à casa onde se \nencontrava a peça atacante. A captura da peça só é valida se a \npeça não estiver protegida\n\nPecas protegidas: \n\t\n       1 - Casas especiais:As casas 26, 28 e 29 são casas marcadas no \n    tabuleiro que oferecem proteção, se uma peça estiver sobre uma \n    destas casas não pode ser capturada\n\n       2 - Blocos: Se duas peças da mesma cor estivem em  casas \n    adjacente formam um bloco que impede que estas sejam \n    capturadas pelo adversário.\n\n       3 - Muralhas:Três peças ou mais da mesma cor formam uma \n    muralha. Tal como nos blocos, as peças que formam uma muralha \n    não podem ser capturadas, para além disso não podem ser \n    transpostas pelas peças do adversário.\n\nA última regra é a casa armadilha.\nSe uma peça for parar à casa nr 27, ou areias movediças, é forçada \na recuar até à 16. Caso esta esteja ocupada o jogador deve lançar o \ndado e o valor que obter é o numero da casa do inicio do tabuleiro \nonde irá recolocar a peça em jogo.");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Instruções", jPanel5);

        jLabel6.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SENET");

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel11Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mensagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel11Layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(mensagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel11, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel11, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novojogoIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojogoIAActionPerformed
        // TODO add your handling code here:
        panel11.modo=3;
        options.setVisible(false);
        panel11.repaint();
    }//GEN-LAST:event_novojogoIAActionPerformed

    private void NovojogopvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovojogopvpActionPerformed
        // TODO add your handling code here:
        panel11.modo=0;
        options.setVisible(false);
        panel11.repaint();
    }//GEN-LAST:event_NovojogopvpActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        ObjectInputStream in = null;
        Jogo load;
        try {
            FileInputStream fileIn = new FileInputStream("senet.ser");
            in = new ObjectInputStream(fileIn);
            load = (Jogo) in.readObject();
            in.close();
            
            panel11.jogo=load;
            panel11.jogoBackup=load;
            panel11.modo=load.modoBackup;
            panel11.casa='X';
            if(load.getPrimeiro()){panel11.nextPlayer=load.actual().getCor();}
            else{panel11.nextPlayer=!load.actual().getCor();}
            panel11.mensagem=load.mensagemBackup;
        }catch(IOException i){
		
	}catch(ClassNotFoundException c){
		System.out.println(".Labirinto class not found.");
	}
        mensagemLabel.setText(panel11.mensagem);
        height=this.getHeight();
        lol=1*height/29;
        mensagemLabel.setFont(new java.awt.Font("Tahoma", 0, lol));
        panel11.repaint();
        options.setVisible(false);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        options.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        ObjectOutputStream out = null;
        panel11.jogoBackup=panel11.jogo;
        panel11.jogoBackup.modoBackup=panel11.modo;
        panel11.jogoBackup.mensagemBackup=panel11.mensagem;
        Jogo save=panel11.jogoBackup;
        try {
           FileOutputStream fileOut = new FileOutputStream("senet.ser"); 
                out = new ObjectOutputStream(fileOut);
                out.writeObject(save);
                out.close();
            
        }catch(IOException i)
		{
			i.printStackTrace();
		}

        
					         
    }//GEN-LAST:event_saveButtonActionPerformed

    private void panel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel11MouseClicked
        // TODO add your handling code here:
        if(panel11.casa=='O'){
            options.setVisible(true);
        }
        mensagemLabel.setText(panel11.mensagem);
        height=this.getHeight();
        lol=1*height/29;
        mensagemLabel.setFont(new java.awt.Font("Tahoma", 0, lol));

    }//GEN-LAST:event_panel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Jframe().setVisible(true);
                
                
            }
        });
         
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Novojogopvp;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel mensagemLabel;
    private javax.swing.JButton novojogoIA;
    private javax.swing.JPanel options;
    private gui.Panel66 panel11;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    
}
